version: '3.8'


volumes:
  minio_data:
    driver: local

services:
  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_USER}
    env_file:
      - .env

  flask-app:
    build: .
    container_name: flask-app
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - ./:/app
    depends_on:
      - minio
