dynaconf_merge = true

[default]
    mode = "default"

    [default.minio]
        SECRET_KEY = "minioadmin"

    [default.mongo]
        PASSWORD = ".IIIMinexoraIII."

[development]
    mode = "development"

    [development.minio]
        SECRET_KEY = "minioadmin"

    [development.mongo]
        PASSWORD = ".IIIMinexoraIII."

[test]
    mode = "test"

    [test.minio]
        SECRET_KEY = "minioadmin"

    [test.mongo]
        PASSWORD = ".IIIMinexoraIII."

[production]
    mode = "production"

    [production.minio]
        SECRET_KEY = "minioadmin"

    [production.mongo]
        PASSWORD = ".IIIMinexoraIII."