dynaconf_merge = true

[default]
    mode = "default"

    [default.minio]
        SECRET_KEY = "minioadmin"


[development]
    mode = "development"

    [development.minio]
        SECRET_KEY = "minioadmin"



[test]
    mode = "test"

    [test.minio]
        SECRET_KEY = "minioadmin"



[production]
    mode = "production"

    [production.minio]
        SECRET_KEY = "minioadmin"

    