dynaconf_merge = true

[default]
    mode = "default"

    [default.minio]
        ACCESS_KEY = "minioadmin"
        BUCKET_NAME = "my-bucket"
        HOST = "localhost"
        PORT = "9000"
        SHARE_TIME = 12

    [default.shortner]
        URL_LENGTH = 6

    [default.flask]
        HOST = "127.0.0.1"
        PORT = 5000
        DEBUG = true

    [default.mongo]
        USER = "Minexora"
        DATABASE = "Minio"
        HOST = "127.0.0.1"
        PORT = 27017    
        TIMEOUT = 5000


[development]
    mode = "development"

    [development.minio]
        ACCESS_KEY = "minioadmin"
        BUCKET_NAME = "my-bucket"
        HOST = "localhost"
        PORT = "9000"
        SHARE_TIME = 12

    [development.shortner]
        URL_LENGTH = 6

    [development.flask]
        HOST = "127.0.0.1"
        PORT = 5000
        DEBUG = true

    [development.mongo]
        USER = "Minexora"
        DATABASE = "Minio"
        HOST = "127.0.0.1"
        PORT = 27017    
        TIMEOUT = 5000  


[test]
    mode = "test"

    [test.minio]
        ACCESS_KEY = "minioadmin"
        BUCKET_NAME = "my-bucket"
        HOST = "localhost"
        PORT = "9000"
        SHARE_TIME = 12

    [test.shortner]
        URL_LENGTH = 6

    [test.flask]
        HOST = "0.0.0.0"
        PORT = 5000
        DEBUG = false

    [test.mongo]
        USER = "Minexora"
        DATABASE = "Minio"
        HOST = "127.0.0.1"
        PORT = 27017    
        TIMEOUT = 5000


[production]
    mode = "production"

    [production.minio]
        ACCESS_KEY = "minioadmin"
        BUCKET_NAME = "my-bucket"
        HOST = "192.168.33.83"
        PORT = "9000"
        SHARE_TIME = 12


    [production.shortner]
        URL_LENGTH = 6
        
    [production.flask]
        HOST = "0.0.0.0"
        PORT = 5000
        DEBUG = false

    [production.mongo]
        USER = "Minexora"
        DATABASE = "Minio"
        HOST = "mongo"
        PORT = 27017     
        TIMEOUT = 5000 
